title: "Nitin Gupta"
description: "Tech, Travel, Books, and Quotes"
url: "https://nitingupta.in"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-archives

author:
  name: "Nitin Gupta"
  bio: "Exploring the intersections of tech, journeys, and words."
  location: "India"
  email: "gupta.nitin015@gmail.com"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/guptanitin15"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/guptanitin15"

minimal_mistakes_skin: "default"

paginate: 5
paginate_path: "/page:num/"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: true
